spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://10.0.1.110:3306/whenyourcar
    username: user
    password: '@Opyuhepl758'
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: 10.0.1.23
      port: 6379

server:
  port: 8080



