spring:
  application:
    name: whenyourcar-local
  datasource:
    url: jdbc:mysql://localhost:3306/whenyourcar
    username: root
    password: 0782
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
    rabbitmq:
      host: localhost
      port: 5672
      username: guest
      password: guest
      virtual-host: /

stomp:
  relay:
    host: localhost
    port: 61613

server:
  port: 8080



